### PR TITLE
feat/opt-parser: add parser to read non-standard oc from MG

### PR DESCRIPTION
**Pull request by mtulio**
Hey @kxr!
First of all, I would like to congrats for the amazing project, it is very helpful for me every day! =)

I would like to introduce `omg parser [command]` to parse files available on must-gather but it's not part of `oc` cli.

The main idea is to parse files to be easy to review and avoid requesting extra commands when investigating some issues.

One example is etcd information, the `healty`,` member list` and `status` of etcd is already on must-gather and could be parsed to a "human readable" as we have when running `etcdctl` commands. It's already gathered by [script] (https://github.com/openshift/must-gather/blob/master/collection-scripts/gather_etcd) and is available in a subdirect `etcd_info` from root of must-gather.

I develop a generic parser command mapper to be extensible to other files.

I choose to create a new sub-command due to it files is from outside of openshift cli, but let me know if it is good for the purpose of the project, or you already tough in other strategies to retrieve those files to cli.

## Usage

- show available commands:
~~~
$ omg parser -s
COMMAND HELPER
etcd-member-list Parser etcd member list from must-gather etcd_info / member_list.json
etcd-endpoint-health Parser etcd endpoint health from must-gather etcd_info / endpoint_status.json
etcd-endpoint-status Parser etcd endpoint status from must-gather etcd_info / endpoint_status.json
etcd-all Run all etcd commands available

$ omg parser
Missing command argument, avaiable commands:
COMMAND HELPER
etcd-member-list Parser etcd member list from must-gather etcd_info / member_list.json
etcd-endpoint-health Parser etcd endpoint health from must-gather etcd_info / endpoint_status.json
etcd-endpoint-status Parser etcd endpoint status from must-gather etcd_info / endpoint_status.json
etcd-all Run all etcd commands available

$ omg parser CommandNotFound
Command [CommandNotFound] not found, avaiable commands:
COMMAND HELPER
etcd-member-list Parser etcd member list from must-gather etcd_info / member_list.json
etcd-endpoint-health Parser etcd endpoint health from must-gather etcd_info / endpoint_status.json
etcd-endpoint-status Parser etcd endpoint status from must-gather etcd_info / endpoint_status.json
etcd-all Run all etcd commands available

~~~

- execute one command

~~~
$ omg parser etcd-endpoint-status
+ ----------------------------- + ------------------- - + ----------- + ----------- + ------------- + --------- ----- + ------------- + -------------- + --------------- ------- + ---------- + ------------- +
| ENDPOINT | ID | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS | DB IN USE |
| ----------------------------- + ------------------- - + ----------- + ----------- + ------------- + --------- ----- + ------------- + -------------- + --------------- ------- + ---------- + ------------- |
| https://192.168.126.11:2379 | 2338572589395037831 | 3.4.9 | 83.9 MiB | true | false | 5 | 45983 | 45983 | | 47.9 MiB |
+ ----------------------------- + ------------------- - + ----------- + ----------- + ------------- + --------- ----- + ------------- + -------------- + --------------- ------- + ---------- + ------------- +

$ omg parser etcd-all
WANING: ignoring file reader; Is a directory

ClusterID: 2338572589395037831, MemberID: 9836592823016673052, RaftTerm
+ --------------------- + -------------------- + ------ --------------------------- + ---------------------- ----------- +
| ID | name | peerURLs | clientURLs |
| --------------------- + -------------------- + ------ --------------------------- + ---------------------- ----------- |
| 9836592823016673052 | crc-xl2km-master-0 | ['https://192.168.126.11:2380'] | ['https://192.168.126.11:2379'] |
+ --------------------- + -------------------- + ------ --------------------------- + ---------------------- ----------- +
+ ----------------------------- + ---------- + -------- ----- +
| endpoint | health | took |
| ----------------------------- + ---------- + -------- ----- |
| https://192.168.126.11:2379 | True | 14.122873ms |
+ ----------------------------- + ---------- + -------- ----- +
+ ----------------------------- + ------------------- - + ----------- + ----------- + ------------- + --------- ----- + ------------- + -------------- + --------------- ------- + ---------- + ------------- +
| ENDPOINT | ID | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS | DB IN USE |
| ----------------------------- + ------------------- - + ----------- + ----------- + ------------- + --------- ----- + ------------- + -------------- + --------------- ------- + ---------- + ------------- |
| https://192.168.126.11:2379 | 2338572589395037831 | 3.4.9 | 83.9 MiB | true | false | 5 |
~~~

* The tabulation delimiter breaks here (on markdown) but on terminal has a nice view. =)

### CODE REVIEW

**Comment by mtulio** [comment]
Just adding two new subcommands for parser: alerts and alerts-firing

~~~
$ omg parser alerts
+-------------------------------------------+-------------------------------------------------+----------+---------------+----------+
| GroupName                                 | Name                                            | State    |   AlertsCount | Health   |
|-------------------------------------------+-------------------------------------------------+----------+---------------+----------|
| CloudCredentialOperator                   | CloudCredentialOperatorTargetNamespaceMissing   | inactive |             0 | ok       |
| cluster-version                           | CannotRetrieveUpdates                           | inactive |             0 | ok       |
| cluster-version                           | UpdateAvailable                                 | firing   |             1 | ok       |
| openshift-dns.rules                       | CoreDNSPanicking                                | inactive |             0 | ok       |
[...]
| etcd                                      | etcdHTTPRequestsSlow                            | inactive |             0 | ok       |
| general.rules                             | TargetDown                                      | inactive |             0 | ok       |
| general.rules                             | Watchdog                                        | firing   |             1 | ok       |
| kube-apiserver-slos                       | KubeAPIErrorBudgetBurn                          | inactive |             0 | ok       |
[...]
| kubernetes-apps                           | KubeJobCompletion                               | inactive |             0 | ok       |
| kubernetes-apps                           | KubeJobFailed                                   | firing   |             4 | ok       |
| kubernetes-apps                           | KubeHpaReplicasMismatch                         | inactive |             0 | ok       |
[...]
| kubernetes.rules                          | ClusterMonitoringOperatorReconciliationErrors   | inactive |             0 | ok       |
| kubernetes.rules                          | AlertmanagerReceiversNotConfigured              | firing   |             1 | ok       |
| kubernetes.rules                          | MultipleContainersOOMKilled                     | inactive |             0 | ok       |
[...]
| cluster-state-alert.rules                 | CephOSDVersionMismatch                          | inactive |             0 | ok       |
| cluster-state-alert.rules                 | CephMonVersionMismatch                          | firing   |             1 | ok       |
| cluster-utilization-alert.rules           | CephClusterNearFull                             | inactive |             0 | ok       |
[...]
| osd-alert.rules                           | CephPGRepairTakingTooLong                       | inactive |             0 | ok       |
| persistent-volume-alert.rules             | PersistentVolumeUsageNearFull                   | firing   |             2 | ok       |
[...]
+-------------------------------------------+-------------------------------------------------+----------+---------------+----------+
~~~


~~~
$ omg parser alerts-firing
+-------------------------------------------------------------+--------------------------------+---------+-------------------------------------------------------------------+
| Group/AlertName                                             | ActiveAt                       | State   | Details                                                           |
|-------------------------------------------------------------+--------------------------------+---------+-------------------------------------------------------------------|
| cluster-version/UpdateAvailable                             | 2021-04-30T03:08:16.457044785Z | firing  | alertname=UpdateAvailable                                         |
|                                                             |                                |         |  channel=stable-4.6                                               |
|                                                             |                                |         |  endpoint=metrics                                                 |
|                                                             |                                |         |  instance=1.2.3.4:9099                                     |
|                                                             |                                |         |  job=cluster-version-operator                                     |
|                                                             |                                |         |  namespace=openshift-cluster-version                              |
|                                                             |                                |         |  pod=cluster-version-operator-59bbb758bf-5n86c                    |
|                                                             |                                |         |  service=cluster-version-operator                                 |
|                                                             |                                |         |  severity=info                                                    |
|                                                             |                                |         |  upstream=https://api.openshift.com/api/upgrades_info/v1/graph    |
[...]
| logging_fluentd.alerts/FluentdQueueLengthIncreasing         | 2021-05-01T04:27:22.178992472Z | pending | alertname=FluentdQueueLengthIncreasing                            |
|                                                             |                                |         |  container=fluentd                                                |
|                                                             |                                |         |  endpoint=metrics                                                 |
|                                                             |                                |         |  hostname=fluentd-c4d26                                           |
|                                                             |                                |         |  instance=1.2.2.1:24231                                           |
|                                                             |                                |         |  job=fluentd                                                      |
|                                                             |                                |         |  namespace=openshift-logging                                      |
|                                                             |                                |         |  plugin_id=default                                                |
|                                                             |                                |         |  pod=fluentd-c4d26                                                |
|                                                             |                                |         |  service=fluentd                                                  |
|                                                             |                                |         |  severity=critical                                                |
|                                                             |                                |         |  type=elasticsearch                                               |
[...]
| kubernetes-apps/KubeJobFailed                               | 2021-04-30T03:09:40.59085788Z  | firing  | alertname=KubeJobFailed                                           |
|                                                             |                                |         |  condition=true                                                   |
|                                                             |                                |         |  container=kube-rbac-proxy-main                                   |
|                                                             |                                |         |  endpoint=https-main                                              |
|                                                             |                                |         |  instance=1.4.8.8:8443                                            |
|                                                             |                                |         |  job=kube-state-metrics                                           |
|                                                             |                                |         |  job_name=elasticsearch-im-audit-...                              |
|                                                             |                                |         |  namespace=openshift-logging                                      |
|                                                             |                                |         |  pod=kube-state-metrics-...                                       |
|                                                             |                                |         |  service=kube-state-metrics                                       |
|                                                             |                                |         |  severity=warning                                                 |

[...]

| cluster-state-alert.rules/CephMonVersionMismatch            | 2021-04-26T23:47:04.41118183Z  | firing  | alertname=CephMonVersionMismatch                                  |
|                                                             |                                |         |  severity=warning                                                 |
| persistent-volume-alert.rules/PersistentVolumeUsageNearFull | 2021-04-30T03:09:53.55755077Z  | firing  | alertname=PersistentVolumeUsageNearFull                           |
|                                                             |                                |         |  endpoint=https-metrics                                           |
|                                                             |                                |         |  instance=1.2.3.4:10250                                           |
|                                                             |                                |         |  job=kubelet                                                      |
|                                                             |                                |         |  metrics_path=/metrics                                            |
|                                                             |                                |         |  namespace=openshift-logging                                      |
|                                                             |                                |         |  node=infra3.example.com                                          |
|                                                             |                                |         |  persistentvolumeclaim=elasticsearch-elasticsearch-cdm-....-2 |
|                                                             |                                |         |  provisioner=openshift-storage.rbd.csi.ceph.com                   |
|                                                             |                                |         |  service=kubelet                                                  |
|                                                             |                                |         |  severity=warning                                                 |
|                                                             |                                |         |  storageclass=ocs-storagecluster-ceph-rbd                         |

~~~

**Comment by kxr** [comment]
@mtulio Wow, this looks very useful. Thanks a lot for the pull requests. I will review them and merge them. Thanks again :+1:

**Comment by kxr** [comment]
@mtulio I appologize for the delay. I got really busy with my official work. It looks like I will be getting some free time soon.

**Comment by kxr** [comment]
So I have thought about this more. And I agree with you that we should keep the non-oc commands separate from oc commands (like `oc get` etc.).

In my opinion `show` fits better for this sub command rather than `parser`. E.g, `omg show alerts`, `omg show alerts-firing`, `omg show etcd-member-list` etc.

Right now, I am restructuring the code to support more modularity and handle multiple must-gather directories at the same time. I will merge this PR directly for now and modify and adopt this feature in the upcoming restructured release (v2).

**Comment by mtulio** [comment]
@kxr I agree with you. `omg show subcmd|file` fits better. Additionally we can create a 'default' reader point to full path (`file`) when sending as argument (and subcommand is not defined).

**Pull request merged**
