### PR TITLE
Implementation of 'oc describe nodes'

### PR DESCRIPTION
**Pull request by kevchu3**
This is an initial implementation of `oc describe nodes`, mostly borrowing the framework from `oc get <resource type>`.  There are a few fields that are still unimplemented, namely:
- Roles - just requires some parsing
- Lease - I'm not sure where the lease data comes from

And I figure that by parsing additional YAMLs, the data for the last three can be compiled, but it'll be quite a bit of work for these three:
- Non-terminated Pods
- Allocated resources
- Events

The rest of the fields should all be implemented.

### CODE REVIEW

**Comment by kevchu3** [comment]
@kxr I've implemented `oc describe node` and `oc describe pod` in this go around.  I have some work to do with displaying containers and volumes for pods, but this is a good start.

**Comment by kevchu3** [comment]
I've now also added the events log to `oc describe node` and `oc describe pod`

**Comment by kxr** [comment]
Oh wow @kevchu3 ++ Thank you for this. I am bit busy right now, plus holidays coming up. I will look into this and merge it asap. Thanks again :)

**Comment by kevchu3** [comment]
@kxr No problem, take your time.  The `oc describe pod` is still a work in progress, so I'm implementing it in increments.  In this latest commit, I've implemented most of the container output.

**Comment by kevchu3** [comment]
Finished updates to `oc describe pod`, including implementation of volume mounts.

**Comment by kevchu3** [comment]
@kxr any chance you can take a look at this implementation of oc describe nodes?  It's a fair amount of commit content to review.

**Comment by kxr** [comment]
@kevchu3 yes, I already went through the commits. Thanks a lot for your work. I am just contemplating on some fundamentals of how we implement `describe`. Your work is brilliant and will be useful for the most part, but I might change some basics before incorporating your work.

I am also working on supporting must-gathers that have outputs from [multiple images](https://docs.openshift.com/container-platform/4.4/support/gathering-cluster-data.html#gathering-data-specific-features_gathering-cluster-data). That will, for example slightly change `from_yaml` to gather objects from multiple locations/directories.

Again, thank you for your work :)

**Comment by kevchu3** [comment]
@kxr Hi, just wanted to bump this thread and revisit whether we think this is the approach we should be using with `describe` and/or your progress on any modifications.  I've held off on attempting to implement other potential `describe` functions until you've made a decision going forward.

**Comment by kxr** [comment]
@kevchu3 Sorry the delay. I have merged your work into a separate branch. I will review it and make some changes (for example I don't see the value of having a duplicate from_yaml under desc/ folder). I will give you the feedback along the way.

**Comment by kxr** [comment]
@kevchu3 Hello again. So after merging you PR to a separate branch (kevchu3-describe), I closely examined your code and approach. Though it works, I disagree with your approach. I will elaborate and feel free to disagree :)

There is a lot of duplication of code ([from_yaml](https://github.com/kevchu3/o-must-gather/blob/describe/omg/cmd/desc/from_yaml.py), [desc_main](https://github.com/kevchu3/o-must-gather/blob/describe/omg/cmd/desc_main.py), [resource map](https://github.com/kevchu3/o-must-gather/blob/describe/omg/common/desc_resource_map.py),  etc.). if a functionality is implemented already in "get", there is no harm if describe borrows it from get. Like to read/load an object from yaml file why should describe have its own `from_yaml` function? Similarly why have a separate resource_map for describe? The whole point of "resource mapper" is to be a single point of truth of how we handle things in omg. A better approach would be to add a `desc_func` in the current resource map instead of creating a new one. 

Secondly the desc_main function is a bit overly complicated. Especially [checking for resource types in the desc_main function](https://github.com/kevchu3/o-must-gather/blob/faae283197fbc07378e8b3ae3ae880786885af6c/omg/cmd/desc_main.py#L153-L161) will become a nightmare as we implement other resource types like rolebindings, service accounts and secrets etc.

Anyway, I spend some time and [restructured your implementation](https://github.com/kxr/o-must-gather/commit/0a00178ee9aaae40a0825ca24eddc0ca009f1866). Tell me what you think.

**Comment by kevchu3** [comment]
@kxr Hi, I took a look through your approach and reviewed your code and it's great, I love it!  As the code owner and main contributor, I figured you'd have some great insight into how you envisioned this implementation to flow and how best to refactor the code :)  I did some testing of the new branch and it looks good as well.  When do you feel that this branch can be comfortably merged into main?

As a minor note, one issue I noticed is that `omg describe` without specifying the resource type simply returns `No resources found in XXX namespace` when the error message should probably elaborate that the user has forgotten to specify the resource.  I saw this issue with `omg get` as well, so I'll file a separate issue about it.

**Pull request merged**
