### PR TITLE
Implement a number of new resources and tweaked some displays

### PR DESCRIPTION
**Pull request by kevchu3**
This PR implements `oc get all`, which prints the following resources in the namespace.  To implement this, I also subsequently implemented the missing resources.
- pod
- replicationcontroller
- service
- daemonset
- deployment
- replicaset
- statefulset
- horizontalpodautoscaler **(NEW)**
- job **(NEW)**
- cronjob **(NEW)**
- deploymentconfig
- buildconfig **(NEW)**
- build **(NEW)**
- imagestream **(NEW)**

I also implemented an age2() utility function in `common/helper.py` which compares two timestamps (rather than a timestamp and unix epoch timestamp), and used this in `cmd/get/job_out.py`.

I refactored `cmd/get_main.py` a fair amount, so it's worth a review.

And finally, I sorted the resources in `common/resource_map.py` alphabetically, since we have a rather large list now.

### CODE REVIEW

**Comment by kevchu3** [comment]
Added methods to properly implement `deploymentconfig` and `daemonset`.  Also refactored logic a bit with `cmd/get_main.py` and implemented some display changes to `cmd/get/is_out.py` for consistency with oc cli.

**Comment by kxr** [comment]
@kevchu3 Awesome :+1:  ! I will review it and merge it asap. A bit caught up right now :|

**Comment by kevchu3** [comment]
A few more updates:
- Adding output for customresourcedefinitions, persistentvolumeclaims, endpointslices, replicationcontrollers **(NEW)**
- Sort output for persistentvolumes, storageclasses
- Abbreviate RWO/RWX/ROX for persistentvolumes

**Comment by kxr** [comment]
@kevchu3 Hello, I have reviewed the pull request and thank you once again for the contribution.

All the changes except get_main.py are good to go. The changes in get_main, especially when handling `omg get all`, need some more thinking. For example when if we look at oc's behavior, we should be able to specify `all`  with other object types. For example `oc get all,pvc`.

Another thing I noticed is that we should not print error about "no resources found" when multiple resources are requested. For example if we run `oc get pvc,svc` in a namespace with no pvc, oc will simply show svc but not complain about missing pvc. 

Adding empty lines when showing multiple object types is also a good idea since oc does that and omg is not doing that.

Now I am not sure how to do a selective merge of the pull-request excluding one file. So I am going to merge the pull request and then work on fixing the get_main.py.

Thank you once again.

**Comment by kevchu3** [comment]
@kxr Thanks for reviewing the code.  I did some testing based on your feedback, and found the following:

> For example when if we look at oc's behavior, we should be able to specify all with other object types. For example `oc get all,pvc`.

Looks like an oversight on my end where the list of objects returned in all doesn't include other objects i.e. pvc.  I'll open a fresh issue for it.

> Another thing I noticed is that we should not print error about "no resources found" when multiple resources are requested. For example if we run oc get pvc,svc in a namespace with no pvc, oc will simply show svc but not complain about missing pvc.

I accounted for this in the PR, ran the test below against a project which has an svc but not a pvc:
```
$ ./omg get pvc,svc -n openshift-sdn
NAME         TYPE       CLUSTER-IP  EXTERNAL-IP  PORT(S)   AGE
service/sdn  ClusterIP  None        <none>       9101/TCP  26d
```

> Adding empty lines when showing multiple object types is also a good idea since oc does that and omg is not doing that.

This was some of the logic I reworked in the PR, so test it out, it should look good with the empty lines between objects now.  Here's an example:
```
$ ./omg get pvc,svc -n openshift-image-registry
NAME                                          STATUS  VOLUME           CAPACITY  ACCESS MODES  STORAGECLASS  AGE
persistentvolumeclaim/image-registry-storage  Bound   registry-volume  100Gi     RWX                         12d

NAME                             TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)    AGE
service/image-registry           ClusterIP  172.30.47.147  <none>       5000/TCP   13d
service/image-registry-operator  ClusterIP  None           <none>       60000/TCP  26d
```

**Comment by kevchu3** [comment]
@kxr Thanks for reviewing and merging the code, and I appreciate the thoughtful feedback.  I did some testing based on your feedback, and observed the following:

> For example when if we look at oc's behavior, we should be able to specify all with other object types. For example `oc get all,pvc`.

Looks like an oversight on my end where the list of objects returned in all doesn't include other objects i.e. pvc.  I've opened a fresh issue #21 for it


> Another thing I noticed is that we should not print error about "no resources found" when multiple resources are requested. For example if we run oc get pvc,svc in a namespace with no pvc, oc will simply show svc but not complain about missing pvc.

I accounted for this in the PR, ran the test below against a project which has an svc but not a pvc:
```
$ ./omg get pvc,svc -n openshift-sdn
NAME         TYPE       CLUSTER-IP  EXTERNAL-IP  PORT(S)   AGE
service/sdn  ClusterIP  None        <none>       9101/TCP  26d
```


> Adding empty lines when showing multiple object types is also a good idea since oc does that and omg is not doing that.

This was some of the logic I reworked in the PR, so test it out, it should look good with the empty lines between objects now.  Here's an example:
```
$ ./omg get pvc,svc -n openshift-image-registry
NAME                                          STATUS  VOLUME           CAPACITY  ACCESS MODES  STORAGECLASS  AGE
persistentvolumeclaim/image-registry-storage  Bound   registry-volume  100Gi     RWX                         12d

NAME                             TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)    AGE
service/image-registry           ClusterIP  172.30.47.147  <none>       5000/TCP   13d
service/image-registry-operator  ClusterIP  None           <none>       60000/TCP  26d
```

**Pull request merged**
