### PR TITLE
Updates to 'omg get project'

### PR DESCRIPTION
**Pull request by kevchu3**
Did some work to implement `omg get project` based on issue #4 

At this time, `omg get project` only lists the current project, but the more useful listing of all projects can be still listed with `omg get project -A`, which matches what we are expecting.

### CODE REVIEW

**Comment by kevchu3** [comment]
Also implemented `APIServer`, `Authentication`, `MutatingWebhookConfiguration`, and `ValidatingWebhookConfiguration` resources.

**Comment by kxr** [comment]
@kevchu3 Awesome, thank you for this pull request. I will review it and merge it.

**Comment by kevchu3** [comment]
@kxr Hi Khizer, I've added support for a couple more resources, can you review and merge?

**Comment by kxr** [comment]
Thank you once again and please accept my sincere apology for the delay. I am testing this now and will merge asap.

**Comment by kxr** [comment]
I have merged the pull request.

Though there is one thing that needs to be fixed. If we look at the oc behavior, `omg get project` should get all projects, `-A, --all-namespaces` shouldn't be necessary. But what you did was quick and clever :).

I think we need a special function to read project yamls instead of using the default `from_yaml` function. I will work on that.

Thank you again for your contribution.

**Comment by kxr** [comment]
@kevchu3  Done. See: [8b43fa2](https://github.com/kxr/o-must-gather/commit/8b43fa27e8d01af900652fa3962613954b665145)

**Pull request merged**
